version: '3'

services: 

  mysqldb:
    container_name: mysqldb
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato
      MYSQL_ROOT: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysqldb
    ports:
      - 3307:3306    
    volumes:
      - /home/mysql/data:/var/lib/mysql --user 1000

  app:
    build: .
    container_name: spring_app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tpachato
    restart: on-failure
    links:
      - mysqldb

