version: '3'

services: 

  SonarQube:
    image: sonarqube:8.9.7-community
    depends_on:
      - mysqldb
    environment:
      SONAR_JDBC_URL: jdbc:mysql://mysqldb:3306/tpachato
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: root
    volumes:
      - SonarQube_data:/opt/SonarQube/data
      - SonarQube_extensions:/opt/SonarQube/extensions
      - SonarQube_logs:/opt/SonarQube/logs
    ports:
      - "9000:9000"


  mysqldb:
    container_name: mysqldb1
    image: mysql:5.6
    restart: always
    networks:
      - sonarnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato
      MYSQL_ROOT: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: mysqldb
    ports:
      - 3307:3306    
    volumes:
      - /home/mysql/data:/var/lib/mysql --user 1000

  app:
    build: .
    container_name: spring_app
    ports:
      - "8089:8089"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/tpachato?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tpachato
    restart: on-failure
    links:
      - mysqldb

networks:
  sonarnet:

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins: