services: 
  #config service
  backend-devops:
    build:
     context: ./
    ports: 
      - 8081:8081
    networks:
      - devops
    depends_on:
      - mysqldb
    container_name: backend-devops

  mysqldb:
    image: mysql:5.7
    container_name: mysql-db-devops 
    networks:
        - devops 
    ports: 
       - 3306:3306   
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tpachato 
    
networks:
    devops: