services: 
  #config service
  backend-devops:
    build:
     context: ./
    ports: 
      - 8089:8089
    container_name: backend-devops

version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=tpachato
      - MYSQL_ROOT_PASSWORD=20202
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local